// AUTO-GENERATED by scripts/index-storyboards.mjs — do not edit.
import { Storyboard as SB, type Storyboard } from "@/schema";
import raw0 from "../../storyboards/best-time-to-buy-and-sell-stock.json";
import raw1 from "../../storyboards/container-with-most-water.json";
import raw2 from "../../storyboards/course-schedule.json";
import raw3 from "../../storyboards/invert-binary-tree.json";
import raw4 from "../../storyboards/longest-substring.json";
import raw5 from "../../storyboards/move-zeroes.json";
import raw6 from "../../storyboards/number-of-islands.json";
import raw7 from "../../storyboards/reverse-linked-list.json";
import raw8 from "../../storyboards/two-sum.json";
import raw9 from "../../storyboards/valid-parentheses.json";

const RAW: unknown[] = [raw0, raw1, raw2, raw3, raw4, raw5, raw6, raw7, raw8, raw9];
const NAMES = ["best-time-to-buy-and-sell-stock.json", "container-with-most-water.json", "course-schedule.json", "invert-binary-tree.json", "longest-substring.json", "move-zeroes.json", "number-of-islands.json", "reverse-linked-list.json", "two-sum.json", "valid-parentheses.json"];

function loadAll(): Storyboard[] {
  const out: Storyboard[] = [];
  RAW.forEach((r, i) => {
    const p = SB.safeParse(r);
    if (p.success) out.push(p.data);
    else console.error(`[storyboards] ${NAMES[i]} failed schema:`, p.error.issues.slice(0, 5));
  });
  return out.sort((a, b) => (a.meta.number ?? 0) - (b.meta.number ?? 0));
}

export const ALL_STORYBOARDS: Storyboard[] = loadAll();
export const STORYBOARD_FILES = NAMES;
